In [1]:
import dimod
import numpy as np
import dwave.system

# Solve binary Linear Program as QUBO with default Solver Advantage_system1.1 and Clique Embedding
Problem ID : f0299bbd-4644-47c9-97e1-c9acb153ab01

In [2]:
A = np.array([[0,1,2,3,4,1],
              [2,1,4,1,0,2],
              [1,1,1,1,0,3],
              [1,5,2,3,4,1]])
m, n = A.shape
vartype = dimod.Vartype.BINARY
c = np.array([1,2,1,3,1,4])
b = np.array([1, 3, 2, 6])

# Problem statement:
Given $A\in Z^{mxn}, b\in Z^{m}, c\in Z^{n}$ 

find $x\in F_2^n$ with:

$\min c^T x $ with constraint $Ax=b$ 



This is equivalent to solving QUBO:

$min_x c^Tx + x^T A^T A x - 2 b^TAx + b^Tb$

eventually we need to set weights on the penalty parts $x^T A^T A x - 2 b^TAx + b^Tb$

In [3]:
# Set up linear and quadratic coefficients
L = c.T - 2 * np.matmul(b.T,A)
Q = np.matmul(A.T,A)
offset = b.T.dot(b)

In [4]:
bqm = dimod.as_bqm(L, Q, offset, vartype)

In [5]:
sampler = dwave.system.DWaveCliqueSampler()

In [6]:
sampleset = sampler.sample(bqm,num_reads = 2000)

In [7]:
sampleset.to_pandas_dataframe()

    0  1  2  3  4  5  chain_break_fraction  energy  num_occurrences
0   1  1  0  0  0  0                   0.0     3.0             1370
1   0  1  0  0  0  0                   0.0     8.0              184
2   0  1  0  0  0  1                   0.0    11.0              222
3   0  1  1  0  0  0                   0.0    12.0               76
4   1  0  0  1  0  0                   0.0    12.0               67
5   1  0  0  0  1  0                   0.0    14.0               36
6   0  1  0  1  0  0                   0.0    19.0                5
7   0  0  1  0  0  0                   0.0    20.0                2
8   0  0  0  1  0  0                   0.0    21.0                4
9   1  0  1  0  0  0                   0.0    21.0                5
10  1  1  0  0  0  1                   0.0    22.0                6
11  0  0  0  1  0  1                   0.0    24.0                5
12  0  0  0  0  1  1                   0.0    24.0                6
13  0  0  1  1  0  0                   0.0    25.0                1
14  1  1  0  1  0  0                   0.0    26.0                1
15  0  0  0  0  1  0                   0.0    27.0                1
16  1  0  0  0  1  1                   0.0    27.0                2
17  0  0  1  0  1  0                   0.0    29.0                1
18  0  0  1  0  0  1                   0.0    31.0                1
19  0  1  0  0  1  0                   0.0    33.0                2
20  1  1  0  0  1  0                   0.0    36.0                1
21  0  1  0  1  0  1                   0.0    44.0                1
22  0  1  1  0  0  1                   0.0    45.0                1