## See the paper: Floating Point Calculations on a Quantum Annealer: Division and Matrix Inversion
### Section III Matrix Inversion as a QUBO Problem
Given $M\in R^{NxN}$ with $\det(M)\not=0$ and $Y\in R^{N}$, find $M^{-1}$ to solve the linear equation:
$ M\cdot x = Y \to x=M^{-1}\cdot Y$

In [1]:
import numpy as np
from linear_solver_float import LinearSolverFloat

In [2]:
# set floating point accuracy 
R = 4

In [3]:
# first example
M = np.array([[1/2,3/2],
              [3/2,1/2]])

Y_1 = np.array([1,0])
Y_2 = np.array([0,1])
M_inv = np.linalg.inv(M)

In [4]:
M_inv.dot(Y_1), M_inv.dot(Y_2)

(array([-0.25,  0.75]), array([ 0.75, -0.25]))

In [5]:
num_reads = 1000
lsf = LinearSolverFloat(M,Y_1,R=R,num_reads=num_reads)
sampleset = lsf.sample()
sampleset.to_pandas_dataframe()

    0  1  2  3  4  5  6  7  chain_break_fraction    energy  num_occurrences
0   0  0  1  1  0  1  1  1                   0.0 -12.40625              401
1   0  1  1  1  0  1  1  1                   0.0 -11.90625              305
2   0  1  1  0  0  1  1  1                   0.0 -11.56250               85
3   0  1  0  1  0  1  1  1                   0.0 -11.53125              114
4   0  0  1  0  0  1  1  1                   0.0 -11.43750               11
5   0  0  1  1  0  1  1  0                   0.0 -11.18750               12
6   0  1  1  1  0  1  1  0                   0.0 -11.06250               26
7   0  1  0  0  0  1  1  1                   0.0 -10.87500                8
8   0  0  0  1  0  1  1  1                   0.0 -10.78125                7
9   0  1  1  0  0  1  1  0                   0.0 -10.62500                7
10  0  1  1  1  0  1  0  1                   0.0 -10.53125               13
11  0  1  0  1  0  1  1  0                   0.0 -10.50000                4
12  0  1  1  1  0  0  1  1                   0.0 -10.40625                2
13  0  1  1  0  0  1  0  1                   0.0 -10.00000                1
14  0  1  0  1  0  1  0  1                   0.0  -9.78125                1
15  0  1  1  0  0  0  1  1                   0.0  -9.68750                1
16  0  1  0  1  0  0  1  1                   0.0  -9.28125                1
17  0  1  1  1  0  0  0  1                   0.0  -7.78125                1

In [6]:
min_occurence = num_reads / 20
solutions = lsf.getSolutions(min_occurence)
list(solutions)

[(array([-0.25,  0.75]), -12.40625, 401),
 (array([0.75, 0.75]), -11.90625, 305),
 (array([0.5 , 0.75]), -11.5625, 85),
 (array([0.25, 0.75]), -11.53125, 114)]

In [7]:
lsf.setY(Y_2)
lsf.sample() # 050d68cf-b1d7-4ba5-acdb-688140e88c15
list(lsf.getSolutions(min_occurence))

[(array([ 0.75, -0.25]), -12.40625, 375),
 (array([0.75, 0.75]), -11.90625, 284),
 (array([0.75, 0.5 ]), -11.5625, 114),
 (array([0.75, 0.25]), -11.53125, 116)]