## See the paper: Floating Point Calculations on a Quantum Annealer: Division and Matrix Inversion
### Section III Matrix Inversion as a QUBO Problem
Given $M\in R^{NxN}$ with $\det(M)\not=0$ and $Y\in R^{N}$, find $M^{-1}$ to solve the linear equation:
$ M\cdot x = Y \to x=M^{-1}\cdot Y$

In [1]:
import numpy as np
from linear_solver_float import LinearSolverFloat

In [2]:
# set floating point accuracy 
R = 3

In [3]:
# first example
M = np.array([[3,2],
              [2,1]])

Y_1 = np.array([1,1])
Y_2 = np.array([-1/2,-1/2])
M_inv = np.linalg.inv(M)

In [4]:
M_inv.dot(Y_1), M_inv.dot(Y_2)

(array([ 1., -1.]), array([-0.5,  0.5]))

In [5]:
num_reads = 1000
lsf = LinearSolverFloat(M,Y_1,R=R,num_reads=num_reads)
sampleset = lsf.sample()
sampleset.to_pandas_dataframe()

    0  1  2  3  4  5  chain_break_fraction  energy  num_occurrences
0   0  1  1  0  1  1              0.000000   -52.0              776
1   0  1  1  0  1  0              0.000000   -47.0               60
2   0  0  1  1  1  1              0.000000   -45.5               40
3   0  1  0  0  1  1              0.000000   -45.0               42
4   0  0  1  0  1  1              0.000000   -44.5                9
5   0  1  1  0  0  1              0.000000   -44.5               28
6   0  0  1  1  1  0              0.000000   -41.5                5
7   0  0  1  1  0  1              0.000000   -40.0                4
8   0  0  0  1  1  1              0.000000   -40.0                8
9   0  1  1  1  0  1              0.000000   -39.5                8
10  0  1  0  1  1  1              0.000000   -38.0                5
11  0  1  0  0  1  0              0.000000   -38.0                1
12  0  1  1  1  1  0              0.000000   -37.0                2
13  0  1  1  1  1  1              0.000000   -37.0                2
14  0  1  1  1  0  0              0.000000   -37.0                3
15  0  1  0  1  0  1              0.000000   -36.5                1
16  0  1  0  1  1  0              0.000000   -36.0                2
17  0  1  0  0  0  1              0.000000   -33.5                1
18  0  1  1  0  1  1              0.166667   -52.0                2
19  0  1  1  0  1  1              0.166667   -52.0                1

In [6]:
min_occurence = num_reads / 20
solutions = lsf.getSolutions(min_occurence)
list(solutions)

[(array([0.5, 0.5]), -52.0, 776), (array([0.5, 0. ]), -47.0, 60)]

In [7]:
lsf.setY(Y_2)
lsf.sample() #3cc3c704-57e3-4238-bf4a-3368e3f1a326
list(lsf.getSolutions(min_occurence))

[(array([-0.5,  0.5]), -25.0, 302),
 (array([ 0.5, -0.5]), -19.0, 258),
 (array([-0.5, -0.5]), -18.5, 86),
 (array([ 0. , -0.5]), -15.5, 106)]